//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyerDBapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Lawyer
    {
        [Key]
        public int LawyerID { get; set; }
        [Required(ErrorMessage ="This field is required")]
        //[Column(TypeName ="nvarchar(50)")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        //[Column(TypeName = "varchar(50)")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        //[Column(TypeName = "varchar(6)")]
        public string LSnumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        //[Column(TypeName = "varchar(50)")]
        public string City { get; set; }
        [Required(ErrorMessage = "This field is required")]
        //[Column(TypeName = "varchar(6)")]
        public string PostalCode { get; set; }
        [Required(ErrorMessage = "This field is required")]
        //[Column(TypeName = "varchar(85)")]
        public string LegalService { get; set; }
    }

}
